### ISSUE TITLE
Reddit 503 errors cause bot to go crazy

### ISSUE THREAD

**Issue by rishkar** [rishkar/relert#1]
It might be a good idea to have the bot have a cooldown before it tries reddit again, if it encounters a 503 or similar error

```
Jul  9 19:52:43 apphost00 python3[5479]: Traceback (most recent call last):
Jul  9 19:52:43 apphost00 python3[5479]:  File "/opt/relert/bin/set_alert.py", line 49, in <module>
Jul  9 19:52:43 apphost00 python3[5479]:    for submission in subreddit_con.stream.submissions():
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/praw/models/util.py", line 188, in stream_generator
Jul  9 19:52:43 apphost00 python3[5479]:    for item in reversed(list(function(limit=limit, **function_kwargs))):
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/praw/models/listing/generator.py", line 63, in __next__
Jul  9 19:52:43 apphost00 python3[5479]:    self._next_batch()
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/praw/models/listing/generator.py", line 73, in _next_batch
Jul  9 19:52:43 apphost00 python3[5479]:    self._listing = self._reddit.get(self.url, params=self.params)
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 566, in get
Jul  9 19:52:43 apphost00 python3[5479]:    return self._objectify_request(method="GET", params=params, path=path)
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 673, in _objectify_request
Jul  9 19:52:43 apphost00 python3[5479]:    path=path,
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 856, in request
Jul  9 19:52:43 apphost00 python3[5479]:    json=json,
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 335, in request
Jul  9 19:52:43 apphost00 python3[5479]:    url=url,
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 261, in _request_with_retries
Jul  9 19:52:43 apphost00 python3[5479]:    url,
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 168, in _do_retry
Jul  9 19:52:43 apphost00 python3[5479]:    retry_strategy_state=retry_strategy_state.consume_available_retry(),  # noqa: E501
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 261, in _request_with_retries
Jul  9 19:52:43 apphost00 python3[5479]:    url,
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 168, in _do_retry
Jul  9 19:52:43 apphost00 python3[5479]:    retry_strategy_state=retry_strategy_state.consume_available_retry(),  # noqa: E501
Jul  9 19:52:43 apphost00 python3[5479]:  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 264, in _request_with_retries
Jul  9 19:52:43 apphost00 python3[5479]:    raise self.STATUS_EXCEPTIONS[response.status_code](response)
Jul  9 19:52:43 apphost00 python3[5479]: prawcore.exceptions.ServerError: received 503 HTTP response
```

**Comment by rishkar** [comment]
This was resolved in 80cb12591fe3dc92f90b6b3ee16ec5e590722a5f
